spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: werothesnsmc21th@gmail.com
    password: fzjf dvdk xgjs wglb
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
  file:
    upload:
      path: C:/fileUpload/
      url: http://localhost:8080/file/
jwt:
  secret: 7cb557e20f15ebac9442a240481c50e45118909be31f7a6c553b09a189034eeb53c862aaf55e2fef762972390ec43c7162cd941238a986c5ea1e55a887e67d9e
  token-validity-in-seconds: 86400

