spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 76065633
  jpa:
    hibernate:
      ddl-auto: create
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect
  jwt:
    secretKey: 21df42sk421a42d14g5342n6jkd757ds8a658fnvk796cdsd769sa57k4f532j5d23s7a73k5w84erj4kaf23l52d152srt