spring:
  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         kakao:
  #           client-id: 821f82631a54c06b4e9da0edfc48a887
  #           client-secret: 8rIPWShuR2IivwAkCcD7fU9fEAWYwja2
  #           authorization-grant-type: authorization_code
  #           redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
  #           client-name: Kakao
  #           scope: profile, account_email
  #           client-authentication-method: client_secret_post
  #           provider: kakao
  #         naver:
  #           client-id: Nw4odBgsAgD7cFUqdnwy
  #           client-secret: g6sO1pG_EI
  #           authorization-grant-type: authorization_code
  #           redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
  #           client-name: Naver
  #           scope: name, email
  #           client-authentication-method: post
  #           provider: naver
  #       provider:
  #         kakao:
  #           authorization-uri: https://kauth.kakao.com/oauth/authorize
  #           token-uri: https://kauth.kakao.com/oauth/token
  #           user-info-uri: https://kapi.kakao.com/v2/user/me
  #           user-name-attribute: id
  #         naver:
  #           authorization-uri: https://nid.naver.com/oauth2.0/authorize
  #           token-uri: https://nid.naver.com/oauth2.0/token
  #           user-info-uri: https://openapi.naver.com/v1/nid/me
  #           user-name-attribute: response
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=true
    username: developer
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com # Gmail SMTP 서버 호스트
    port: 587 # Gmail SMTP 서버 포트
    username: tksg878@gmail.com # 이메일 계정 사용자 이름
    password: ejsu xwee jgjk oasb # 이메일 계정 비밀번호
    protocol: smtp # 사용할 프로토콜 (일반적으로 smtp 사용)
    properties:
      mail.smtp:
        auth: true # SMTP 인증 사용 여부
        starttls.enable: true # STARTTLS 사용 여부 (Gmail은 필수)

jwt:
  secretKey: 21df42sk421a42d14g5342n6jkd757ds8a658fnvk796cdsd769sa57k4f532j5d23s7a73k5w84erj4kaf23l52d152srt

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    com.yourcompany: DEBUG
