spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5c8efbc29bf458a085ef5639c786c78b
            client-secret: YCaJS0u4DQmGhfkTY31qLOxXRTktFZ6g
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
          naver:
            client-id: JDLLteklQS3Ogwy2fnFS
            client-secret: ftMQGsRJlq
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    url: jdbc:mysql://127.0.0.1/test2
    username: root
    password: 76065633
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: werothesnsmc21th@gmail.com
    password: yqey wztb lglo fvag
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
jwt:
  secret: 7cb557e20f15ebac9442a240481c50e45118909be31f7a6c553b09a189034eeb53c862aaf55e2fef762972390ec43c7162cd941238a986c5ea1e55a887e67d9e
  token-validity-in-seconds: 86400