name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create application.yml file
        run: echo "${{ secrets.BE_APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: Test & build
        run: ./gradlew clean build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t wero-server .

      - name: Tag Docker image
        run: docker tag wero-server ${{ steps.login-ecr.outputs.registry }}/wero-server:latest

      - name: Push Docker image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/wero-server:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop wero-server || true
            docker rm wero-server || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/wero-server:latest
            docker run -d --name wero-server -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/wero-server:latest
